### ISSUE TITLE
错误: 程序包com.tchip.tachograph不存在

### ISSUE THREAD

**Issue by jp1017** [zhoumushui/CarLauncher#1]
![qq 20160303112526](https://cloud.githubusercontent.com/assets/7868514/13483794/a7d1b7ec-e132-11e5-8b93-253465df2e34.jpg)

少包。。。

**Comment by zhoumushui** [comment]
`com.tchip.tachograph`这个包集成到了系统里，通过加载静态Java类库调用：
`LOCAL_STATIC_JAVA_LIBRARIES := com.tchip.tachograph`
这个应用也是内置到`system/priv-app/`下的。

**Comment by jp1017** [comment]
你好，这个库需要自己修改吗?
搜到了你的博客：
http://blog.csdn.net/zhoumushui/article/details/48974091
请问你也是做车载的吗?

**Comment by jp1017** [comment]
我注释掉了这些，可以运行了，并移植到了 android studio：

https://github.com/jp1017/CarLauncher/tree/master
